name = "anastasialabs/upgradable-multisig"
version = "0.0.1"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'anastasialabs/upgradable-multisig'"

[repository]
user = "anastasialabs"
project = "upgradable-multisig"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"   
source = "github"

[[dependencies]]
name = "anastasia-labs/aiken-design-patterns"
version = "38997fc"
source = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.1"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config]
