name = "anastasialabs/upgradable-multisig"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'anastasialabs/upgradable-multisig'"

[repository]
user = "anastasialabs"
project = "upgradable-multisig"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
